# Site settings
title: HL Blog
SEOTitle: 海龙的博客 | HL Blog
header-img: img/post-bg-desk.jpg
email: whllotus@qq.com
description: "As the saying goes,Where there is a will,there is a way"
keyword: "whl, whl Blog, 海龙的博客, wuhailong, 武海龙, machine learning, deep learning, nlp,cv,c++,python,java"
url: "http://lotuswhl.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lotuswhl/lotuswhl.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "life without learning is so so boring"
sidebar-avatar: /img/about-HL-gentle.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     lotuswhl
github_username:    lotuswhl
#facebook_username:  baiying.qiu.7
jianshu_username:   4ec51efe2c9a
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: lotuswhl

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 0081b5dd2db1dbde6538                            #生成的clientID
  clientSecret: 160854bb6cc5986d17d7ce005d632fc332ddc61d    #生成的clientSecret
  repo: lotuswhl.github.io    #仓库名称
  owner: lotuswhl    #github用户名
  admin: lotuswhl
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: c8a5418ab995bcf64d7298c3b08c252a

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "lotuswhl csdn blog",
        href: "https://blog.csdn.net/dragonboss2016"
    },{
        title: "lotuswhl wordpress blog",
        href: "https://lotuswhl.wordpress.com"
    }
]
